language: node_js

node_js:
  - 8

#before_install:
#  openssl aes-256-cbc -K $encrypted_50f1fbeadf05_key -iv $encrypted_50f1fbeadf05_iv -in server/firebase-access.json.enc -out server/firebase-access.json -d

# blocklist
# branches:
#   except:
#     - master

install:
  - npm install

script:
  - npm run test
